/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bab10;

import Bab9.*;
import Bab8.*;

/**
 *
 * @author USER
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        Home = new javax.swing.JMenu();
        form = new javax.swing.JMenu();
        GUI_Makanan = new javax.swing.JMenuItem();
        GUI_Minuman = new javax.swing.JMenuItem();
        GUI_kamar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Home.setText("Home");
        jMenuBar1.add(Home);

        form.setText("Form");
        form.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formActionPerformed(evt);
            }
        });

        GUI_Makanan.setText("Makanan");
        GUI_Makanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUI_MakananActionPerformed(evt);
            }
        });
        form.add(GUI_Makanan);

        GUI_Minuman.setText("Minuman");
        GUI_Minuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUI_MinumanActionPerformed(evt);
            }
        });
        form.add(GUI_Minuman);

        GUI_kamar.setText("Kamar");
        GUI_kamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUI_kamarActionPerformed(evt);
            }
        });
        form.add(GUI_kamar);

        jMenuBar1.add(form);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formActionPerformed

    private void GUI_MakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUI_MakananActionPerformed
        // TODO add your handling code here:
        gui2 makanan = new gui2();
        makanan.show();
    }//GEN-LAST:event_GUI_MakananActionPerformed

    private void GUI_MinumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUI_MinumanActionPerformed
        // TODO add your handling code here:
        gui21 minuman = new gui21();
        minuman.show();
    }//GEN-LAST:event_GUI_MinumanActionPerformed

    private void GUI_kamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUI_kamarActionPerformed
        // TODO add your handling code here:
        Gui kamar = new Gui();
        kamar.show();
    }//GEN-LAST:event_GUI_kamarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem GUI_Makanan;
    private javax.swing.JMenuItem GUI_Minuman;
    private javax.swing.JMenuItem GUI_kamar;
    private javax.swing.JMenu Home;
    private javax.swing.JMenu form;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
